In [218]:
%matplotlib inline
import matplotlib
import numpy as np
import pickle
import pandas as pd
import matplotlib.pyplot as plt
print('Importing all needed libs')

Importing all needed libs

In [138]:
with open('df.dump', 'rb') as csvfile:
    data = pickle.load(csvfile)
    all_bookmakers = data.bookmaker.unique()

In [144]:
data.shape

(5584, 6)

In [146]:
data.mean()

rating    3.322773
dtype: float64

In [148]:
data[data.bookmaker==u'ЦУПИС Фонбет'].mean()

rating    3.755766
dtype: float64

In [215]:
no_nan_data = data[~data.bookmaker.isin([u'William Hill', u'Bet365'])]
all_bookmakers = no_nan_data.bookmaker.unique()

array([u'\u0426\u0423\u041f\u0418\u0421 1X\u0421\u0442\u0430\u0432\u043a\u0430',
       u'\u0426\u0423\u041f\u0418\u0421 Leon',
       u'\u0426\u0423\u041f\u0418\u0421 \u041f\u0430\u0440\u0438\u043c\u0430\u0442\u0447',
       u'\u0426\u0423\u041f\u0418\u0421 Betcity',
       u'\u0426\u0423\u041f\u0418\u0421 \u0417\u0435\u043d\u0438\u0442',
       u'\u0426\u0423\u041f\u0418\u0421 \u0411\u0430\u043b\u0442\u0431\u0435\u0442',
       u'\u0426\u0423\u041f\u0418\u0421 \u0424\u043e\u043d\u0431\u0435\u0442',
       u'\u0426\u0423\u041f\u0418\u0421 \u041c\u0430\u0440\u0430\u0444\u043e\u043d',
       u'\u0426\u0423\u041f\u0418\u0421 \u041b\u0438\u0433\u0430 \u0421\u0442\u0430\u0432\u043e\u043a',
       u'\u0426\u0423\u041f\u0418\u0421 Winline',
       u'\u0426\u0423\u041f\u0418\u0421 \u041e\u043b\u0438\u043c\u043f',
       u'\u0426\u0423\u041f\u0418\u0421 BingoBoom',
       u'\u0426\u0423\u041f\u0418\u0421 888.ru',
       u'\u0426\u0423\u041f\u0418\u0421 Tennisi',
       u'\u0426\u0423\u041f\u0418\u0421 Bwin.ru',
       u'\u0426\u0423\u041f\u0418\u0421 \u041c\u043e\u0441\u0442\u0431\u0435\u0442'],
      dtype=object)

In [237]:
mean_ratings = no_nan_data.groupby(['bookmaker']).rating.agg(['count', 'mean'])
mean_ratings.sort_values(by=['mean', 'count'], ascending=False)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
      <th>mean</th>
    </tr>
    <tr>
      <th>bookmaker</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>ЦУПИС Мостбет</th>
      <td>11</td>
      <td>4.818182</td>
    </tr>
    <tr>
      <th>ЦУПИС Балтбет</th>
      <td>69</td>
      <td>4.195652</td>
    </tr>
    <tr>
      <th>ЦУПИС Bwin.ru</th>
      <td>161</td>
      <td>4.111801</td>
    </tr>
    <tr>
      <th>ЦУПИС Марафон</th>
      <td>247</td>
      <td>3.798381</td>
    </tr>
    <tr>
      <th>ЦУПИС Tennisi</th>
      <td>32</td>
      <td>3.796875</td>
    </tr>
    <tr>
      <th>ЦУПИС Фонбет</th>
      <td>1162</td>
      <td>3.755766</td>
    </tr>
    <tr>
      <th>ЦУПИС Олимп</th>
      <td>329</td>
      <td>3.624924</td>
    </tr>
    <tr>
      <th>ЦУПИС 888.ru</th>
      <td>147</td>
      <td>3.487075</td>
    </tr>
    <tr>
      <th>ЦУПИС BingoBoom</th>
      <td>161</td>
      <td>3.473913</td>
    </tr>
    <tr>
      <th>ЦУПИС 1XСтавка</th>
      <td>306</td>
      <td>3.446078</td>
    </tr>
    <tr>
      <th>ЦУПИС Leon</th>
      <td>550</td>
      <td>3.288000</td>
    </tr>
    <tr>
      <th>ЦУПИС Лига Ставок</th>
      <td>110</td>
      <td>3.281818</td>
    </tr>
    <tr>
      <th>ЦУПИС Париматч</th>
      <td>998</td>
      <td>3.027956</td>
    </tr>
    <tr>
      <th>ЦУПИС Зенит</th>
      <td>42</td>
      <td>2.928571</td>
    </tr>
    <tr>
      <th>ЦУПИС Winline</th>
      <td>147</td>
      <td>2.605442</td>
    </tr>
    <tr>
      <th>ЦУПИС Betcity</th>
      <td>635</td>
      <td>2.401102</td>
    </tr>
  </tbody>
</table>
</div>

In [240]:
median_ratings = no_nan_data.groupby(['bookmaker']).rating.agg(['count', 'median'])
median_ratings.sort_values(by=['median', 'count'], ascending=False)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
      <th>median</th>
    </tr>
    <tr>
      <th>bookmaker</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>ЦУПИС Балтбет</th>
      <td>69</td>
      <td>5.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Tennisi</th>
      <td>32</td>
      <td>5.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Мостбет</th>
      <td>11</td>
      <td>5.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Олимп</th>
      <td>329</td>
      <td>4.30</td>
    </tr>
    <tr>
      <th>ЦУПИС Фонбет</th>
      <td>1162</td>
      <td>4.10</td>
    </tr>
    <tr>
      <th>ЦУПИС Марафон</th>
      <td>247</td>
      <td>4.10</td>
    </tr>
    <tr>
      <th>ЦУПИС BingoBoom</th>
      <td>161</td>
      <td>4.10</td>
    </tr>
    <tr>
      <th>ЦУПИС 1XСтавка</th>
      <td>306</td>
      <td>4.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Bwin.ru</th>
      <td>161</td>
      <td>4.00</td>
    </tr>
    <tr>
      <th>ЦУПИС 888.ru</th>
      <td>147</td>
      <td>4.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Лига Ставок</th>
      <td>110</td>
      <td>4.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Зенит</th>
      <td>42</td>
      <td>3.75</td>
    </tr>
    <tr>
      <th>ЦУПИС Leon</th>
      <td>550</td>
      <td>3.70</td>
    </tr>
    <tr>
      <th>ЦУПИС Париматч</th>
      <td>998</td>
      <td>3.40</td>
    </tr>
    <tr>
      <th>ЦУПИС Winline</th>
      <td>147</td>
      <td>3.00</td>
    </tr>
    <tr>
      <th>ЦУПИС Betcity</th>
      <td>635</td>
      <td>2.10</td>
    </tr>
  </tbody>
</table>
</div>

In [241]:
aggregated_ratings = no_nan_data.groupby(['bookmaker']).rating.agg(['count', 'median', 'mean'])
aggregated_ratings.sort_values(by=['median', 'mean', 'count'], ascending=False)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
      <th>median</th>
      <th>mean</th>
    </tr>
    <tr>
      <th>bookmaker</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>ЦУПИС Мостбет</th>
      <td>11</td>
      <td>5.00</td>
      <td>4.818182</td>
    </tr>
    <tr>
      <th>ЦУПИС Балтбет</th>
      <td>69</td>
      <td>5.00</td>
      <td>4.195652</td>
    </tr>
    <tr>
      <th>ЦУПИС Tennisi</th>
      <td>32</td>
      <td>5.00</td>
      <td>3.796875</td>
    </tr>
    <tr>
      <th>ЦУПИС Олимп</th>
      <td>329</td>
      <td>4.30</td>
      <td>3.624924</td>
    </tr>
    <tr>
      <th>ЦУПИС Марафон</th>
      <td>247</td>
      <td>4.10</td>
      <td>3.798381</td>
    </tr>
    <tr>
      <th>ЦУПИС Фонбет</th>
      <td>1162</td>
      <td>4.10</td>
      <td>3.755766</td>
    </tr>
    <tr>
      <th>ЦУПИС BingoBoom</th>
      <td>161</td>
      <td>4.10</td>
      <td>3.473913</td>
    </tr>
    <tr>
      <th>ЦУПИС Bwin.ru</th>
      <td>161</td>
      <td>4.00</td>
      <td>4.111801</td>
    </tr>
    <tr>
      <th>ЦУПИС 888.ru</th>
      <td>147</td>
      <td>4.00</td>
      <td>3.487075</td>
    </tr>
    <tr>
      <th>ЦУПИС 1XСтавка</th>
      <td>306</td>
      <td>4.00</td>
      <td>3.446078</td>
    </tr>
    <tr>
      <th>ЦУПИС Лига Ставок</th>
      <td>110</td>
      <td>4.00</td>
      <td>3.281818</td>
    </tr>
    <tr>
      <th>ЦУПИС Зенит</th>
      <td>42</td>
      <td>3.75</td>
      <td>2.928571</td>
    </tr>
    <tr>
      <th>ЦУПИС Leon</th>
      <td>550</td>
      <td>3.70</td>
      <td>3.288000</td>
    </tr>
    <tr>
      <th>ЦУПИС Париматч</th>
      <td>998</td>
      <td>3.40</td>
      <td>3.027956</td>
    </tr>
    <tr>
      <th>ЦУПИС Winline</th>
      <td>147</td>
      <td>3.00</td>
      <td>2.605442</td>
    </tr>
    <tr>
      <th>ЦУПИС Betcity</th>
      <td>635</td>
      <td>2.10</td>
      <td>2.401102</td>
    </tr>
  </tbody>
</table>
</div>